project_name: "YoChameleon2"
entity: "thaoshibe-university-of-wisconsin-madison"

model_id: 'leloy/Anole-7b-v0.1-hf'
data_root: '/mnt/localssd/code/data/minithao/'

json_file:
  - './json/16-4.json' # Remember to change this

sks_name: 'thao'
prefix_token: 16 # Remember to change this
exp_name: 'neg-16-4' # Remember to change this

spacing: 4

iteration: 1001
save_every: 100

batch_size: 4
savedir: '/sensei-fs/users/thaon/ckpt/'
whole_model: False
tokenizer_max_length: 1500
eval_visualization: True

resume:
  resume: False
  resume_iteration: 150
  savedir: '/sensei-fs/users/thaon/ckpt/' 
  exp_name: 'thao-8'
  sks_name: 'thao'
  sequential_learning: False
  spacing: 8

optimizer:
  type: 'AdamW'
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 1e-4
  eps: 1e-6
  grad_clip: 0.5

scheduler:
  type: 'StepLR'
  step_size: 10
  gamma: 0.05

special_tokens:
  START_OF_IMAGE_INDEX: 8197
  END_OF_IMAGE_INDEX: 8196
  END_OF_TURN: 8710
  PAD_INDEX: 1
  PERSONALITY_TOKEN: '<reserved16200>'

# --- TEST CONFIG --- 
test:
  prompt: "A photo of <reserved16200>."
  iteration: 0
  save_dir: '/sensei-fs/users/thaon/generated_images/'
  batch_size: 16
  num_images: 32
