model_id: 'leloy/Anole-7b-v0.1-hf'
data_root: '/mnt/localssd/code/data/minibo/inpainted/'
json_file: './example_training_data/v5/bo-qa.json'

sks_name: 'bo'
prefix_token: 16

epoch: 101
batch_size: 3
savedir: './ckpt'
exp_name: 'v5-qa'
save_every: 5