model_id: 'leloy/Anole-7b-v0.1-hf'
data_root: '/mnt/localssd/code/data/minibo/'
json_file:
  # - '/mnt/localssd/code/data/minibo/text-conversation.json'
  # - '/mnt/localssd/code/data/minibo/laion_reference.json'
  # # - '/mnt/localssd/code/data/minibo/recognition.json'
  # - '/mnt/localssd/code/data/minibo/inpainted.json'
  - '/mnt/localssd/code/YoChameleon/create-training-data/ranking.json'
sks_name: 'bo'
prefix_token: 16

epoch: 150
batch_size: 4
savedir: './ckpt'
exp_name: 'bo-v4'
save_every: 2
whole_model: "False"