model_id: 'leloy/Anole-7b-v0.1-hf'
data_root: '/mnt/localssd/code/data/minibo/'
json_file:
  - '/mnt/localssd/code/YoChameleon/example_training_data/v1/6_ranked.json'
  - '/mnt/localssd/code/YoChameleon/example_training_data/v1/7_ranked.json'
  - '/mnt/localssd/code/YoChameleon/example_training_data/v1/8_ranked.json'
  - '/mnt/localssd/code/YoChameleon/example_training_data/v1/9_ranked.json'
  - '/mnt/localssd/code/YoChameleon/example_training_data/v1/real.json'

sks_name: 'bo'
prefix_token: 16

epoch: 150
batch_size: 8
savedir: './ckpt'
exp_name: 'bo-v1'
save_every: 2
whole_model: "False"