model_id: 'leloy/Anole-7b-v0.1-hf'
data_root: '/mnt/localssd/code/data/minimam/inpainted/'
json_file: './example_training_data/v5/mam.json'

sks_name: 'mam'
prefix_token: 16

epoch: 101
batch_size: 3
savedir: './ckpt'
exp_name: 'v5'
save_every: 5