model_id: 'leloy/Anole-7b-v0.1-hf'
data_root: '/mnt/localssd/code/data/minithao/'
json_file:
  - '/mnt/localssd/code/data/dathao/conversations-real.json'

sks_name: 'thao'
prefix_token: 16

epoch: 150
batch_size: 6
savedir: '/sensei-fs/users/thaon/ckpt/'
exp_name: 'thao-real'
save_every: 5
whole_model: False

resume: False
resume_epoch: 20