model_id: 'leloy/Anole-7b-v0.1-hf'
data_root: '/mnt/localssd/code/data/minithao/'
json_file:
  - '/sensei-fs/users/thaon/data/yollava-data/train/thao/conversations-v4.json'

sks_name: 'thao'
prefix_token: 16

epoch: 150
batch_size: 6
savedir: '/sensei-fs/users/thaon/ckpt/'
exp_name: 'thao-v4'
save_every: 5
whole_model: False

resume: False
resume_epoch: 20