project_name: "YoChameleon"
model_id: 'leloy/Anole-7b-v0.1-hf'
data_root: '/mnt/localssd/code/data/minithao/'
json_file:
  - '/mnt/localssd/code/data/dathao_algined/conversations-v3.json'

sks_name: 'thao'
prefix_token: 128

iteration: 1501
batch_size: 4
savedir: '/mnt/localssd/code/YoChameleon/ckpt'
exp_name: 'thao-v3'
save_every: 50
whole_model: False

resume: False
resume_epoch: 20