model_id: 'leloy/Anole-7b-v0.1-hf'
data_root: '/mnt/localssd/code/data/minithao/'
json_file:
  - '/mnt/localssd/code/data/dathao_algined/conversations-real_aligned.json'

sks_name: 'thao'
prefix_token: 16

epoch: 150
batch_size: 8
savedir: '/mnt/localssd/code/YoChameleon/ckpt'
exp_name: 'thao-real-lr00002'
save_every: 15
whole_model: True

resume: False
resume_epoch: 20

lr: 0.00001
iteration: 120