model_id: 'leloy/Anole-7b-v0.1-hf'
data_root: '/mnt/localssd/code/data/minithao/'
json_file:
  - '/mnt/localssd/code/data/minithao/piat_retrieved/6_ranked.json'
  - '/mnt/localssd/code/data/minithao/piat_retrieved/3_ranked.json'
  - '/mnt/localssd/code/data/minithao/piat_retrieved/5_ranked.json'
  - '/mnt/localssd/code/data/minithao/piat_retrieved/9_ranked.json'
  - '/mnt/localssd/code/data/minithao/piat_retrieved/real.json'

sks_name: 'thao'
prefix_token: 16

epoch: 150
batch_size: 8
savedir: './ckpt'
exp_name: 'thao-v1'
save_every: 2
whole_model: "False"