model_id: 'leloy/Anole-7b-v0.1-hf'
data_root: '/mnt/localssd/code/data/minithao/'
json_file:
  - '/mnt/localssd/code/data/minithao/piat_retrieved/0_ranked.json'
  - '/mnt/localssd/code/data/minithao/piat_retrieved/1_ranked.json'
  - '/mnt/localssd/code/data/minithao/piat_retrieved/2_ranked.json'
  - '/mnt/localssd/code/data/minithao/piat_retrieved/3_ranked.json'
  - '/mnt/localssd/code/data/minithao/piat_retrieved/real.json'

sks_name: 'yuheng'
prefix_token: 16

epoch: 150
batch_size: 8
savedir: './ckpt'
exp_name: 'yuheng-v1'
save_every: 2
whole_model: "False"